[versions]

# Build constants
compileSdk = "36"
java = "VERSION_17"
material = "1.13.0"
minSdk = "26"
targetSdk = "33"

# AndroidX
appcompat = "1.7.1"
constraintlayout = "2.2.1"
coreKtx = "1.18.0"
navigation = "2.7.7"
room = "2.6.1"

# Testing
espressoCore = "3.5.1"
junit4 = "4.13.2"
junitExt = "1.1.5"

# Static analysis
detekt = "1.23.8"
detektTwitterComposeRules = "0.0.26"
navigationFragmentKtx = "2.10.0"
navigationUiKtx = "2.10.0"

[libraries]

# AndroidX
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# UI
material = { module = "com.google.android.material:material", version.ref = "material" }

# Testing
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junitExt" }

# Static analysis
staticAnalysis-detektApi = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
staticAnalysis-detektCli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
staticAnalysis-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
staticAnalysis-detektLibraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }
staticAnalysis-detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
staticAnalysis-detektTest = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
staticAnalysis-detektTwitterComposeRules = { module = "com.twitter.compose.rules:detekt", version.ref = "detektTwitterComposeRules" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

[bundles]
